### ISSUE TITLE
Bedrock Knowledgebase: Fails when updating chunking strategy

### ISSUE THREAD

**Issue by harmjeff** [awslabs/generative-ai-cdk-constructs#734]
### Describe the bug

Fails to update knowledgebase when changing chunking strategy

### Expected Behavior

When changing:
```python
S3DataSource(
    self,
    construct_id + "DataSource",
    bucket=data_source_bucket.bucket,
    knowledge_base=self.knowledge_base,
    chunking_strategy=ChunkingStrategy.SEMANTIC,
    parsing_strategy=ParsingStategy.foundation_model(
    parsing_model=BedrockFoundationModel.ANTHROPIC_CLAUDE_HAIKU_V1_0.as_i_model(
          self
        )
    ),
)
```

to:
```python
self.data_source = S3DataSource(
     self,
     construct_id + "DataSource",
     bucket=data_source_bucket.bucket,
     knowledge_base=self.knowledge_base,
     chunking_strategy=ChunkingStrategy.DEFAULT,
)
```

The knowledgebase will be updated

### Current Behavior

Error response:
```
4:03:04 PM | UPDATE_FAILED        | AWS::Bedrock::DataSource                  | CustomerServiceAge...DataSource57A98E3A
Resource handler returned message: "DataSource with name s3-ds-backendstackskbdatasource-42d6cd33 already exists. (Service: BedrockAgent, Status Code: 409, Request ID: 522920ab-da42-4188-9e6d-ea41e5e8cc9e)" (RequestTok
en: e1c39da3-8554-a042-25a6-d910c58f8f3d, HandlerErrorCode: AlreadyExists)


 ❌  BackendStackStack failed: Error: The stack named BackendStackStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "DataSource with name s3-ds-backendstackskbdatasource-42d6cd33 already exists. (Service: BedrockAgent, Status Code: 409, Request ID: 522920ab-da42-4188-9e6d-ea41e5e8cc9e)" (RequestToken: e1c39da3-8554-a042-25a6-d910c58f8f3d, HandlerErrorCode: AlreadyExists)
    at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.nvm/versions/node/v20.17.0/lib/node_modules/aws-cdk/lib/index.js:468:10828)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ec2-user/.nvm/versions/node/v20.17.0/lib/node_modules/aws-cdk/lib/index.js:471:200792)
    at async /home/ec2-user/.nvm/versions/node/v20.17.0/lib/node_modules/aws-cdk/lib/index.js:471:182091

 ❌ Deployment failed: Error: The stack named BackendStackStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "DataSource with name s3-ds-backendstackskbdatasource-42d6cd33 already exists. (Service: BedrockAgent, Status Code: 409, Request ID: 522920ab-da42-4188-9e6d-ea41e5e8cc9e)" (RequestToken: e1c39da3-8554-a042-25a6-d910c58f8f3d, HandlerErrorCode: AlreadyExists)
    at FullCloudFormationDeployment.monitorDeployment (/home/ec2-user/.nvm/versions/node/v20.17.0/lib/node_modules/aws-cdk/lib/index.js:468:10828)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/home/ec2-user/.nvm/versions/node/v20.17.0/lib/node_modules/aws-cdk/lib/index.js:471:200792)
    at async /home/ec2-user/.nvm/versions/node/v20.17.0/lib/node_modules/aws-cdk/lib/index.js:471:182091

The stack named BackendStackStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "DataSource with name s3-ds-backendstackskbdatasource-42d6cd33 already exists. (Service: BedrockAgent, Status Code: 409, Request ID: 522920ab-da42-4188-9e6d-ea41e5e8cc9e)" (RequestToken: e1c39da3-8554-a042-25a6-d910c58f8f3d, HandlerErrorCode: AlreadyExists)
```

### Reproduction Steps

See expected behavior

### CDK CLI Version

2.160.0

### Framework Version

0.1.272

### Node.js Version

v20.17.0

### OS

Amazon Linux 2023

### Language

Python

### Language Version

Python 3.12.5

### Region experiencing the issue

us-east-1

### Code modification

No

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by aws-rafams** [comment]
Hi @harmjeff, as you can see from the logs, the causing error for the failed stack is: DataSource with name s3-ds-backendstackskbdatasource-42d6cd33 already exists. This is because the change of chunking implies a replacement (or the recreation of the resource). What is happening is that CloudFormation is trying to create a new Data Source, but since the new resource has the same name as the old one, it cannot create it. This is honestly weird as it should be handled, will look into it.

**Comment by krokoko** [comment]
I will have a look, naming is indeed a probable cause for this issue

**Comment by scottschreckengaust** [comment]
[AWS::Bedrock::DataSource](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrock-datasource-datasourceconfiguration.html) will attempt updates, but fails on certain properties. 

#758 updates the `generatePhysicalNameV2` to take an optional object, `destroyCreate`, to force a destroy and create rather than a replacement. The `S3DataSource` was updated to reflect changes on `chunkingStrategy` or `parsingStrategy` to destroy and create rather than replace.

**Comment by mlnrt** [comment]
Thank you. It saved me quite some time. To destroy and recreate based on changes to chunking configuration, I did it as follow:
```
import { bedrock } from "@cdklabs/generative-ai-cdk-constructs";
import { generatePhysicalNameV2 } from "@cdklabs/generative-ai-cdk-constructs/lib/common/helpers/utils";

const s3ChunkingConfig = { maxTokens: 200, overlapPercentage: 25 };
const s3ChunkingStrategy = bedrock.ChunkingStrategy.fixedSize(s3ChunkingConfig);
const s3DataSource = new bedrock.S3DataSource(this, "s3DataSource", {
  bucket: rawDocsBucket,
  knowledgeBase: knowledgeBase,
  dataSourceName: generatePhysicalNameV2(this, 'docs-',{
    lower: true,
    destroyCreate: JSON.stringify({
      ...s3ChunkingConfig,
      strategy: s3ChunkingStrategy.configuration.chunkingStrategy,
    }),
  }),
  chunkingStrategy: s3ChunkingStrategy,
});
```
